theme = "gruvbox"

[editor]
line-number = "relative"
true-color = true
idle-timeout = 0
completion-trigger-len = 1
whitespace.render = 'all'

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"
